apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: capstone
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: admin
  MONGO_ROOT_PASSWORD: mongoose
  MONGODB_URI: "mongodb://admin:mongoose@mongodb:27017/task-tracker?authSource=admin"

---

apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: capstone
type: Opaque
stringData:
  JWT_SECRET: "YdKPom8MQXWE6Po+fC3fshm+pHJZiDmzbljBLrR+l4snzki7D79IstyUHcGiPqPz"
  JWT_EXPIRES_IN: "7d"
  NODE_ENV: "production"
  CLIENT_URL: "http://capstone-client.capstone.svc.cluster.local"
